name: Demo website deployement

on: 
  push:
    branches:
      -main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Chekout
        uses: actions/checkout@v1

      - name: Cinfigure AWS Credentials
        uses: aws-actions/confiture-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrects.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrects.AWS_SECRET_ACCESS_KEY }}

      - name: Deploy static site to s3 bucket
        run: aws s3 sync . s3://weits-demo --delete

        
          
          
